### ISSUE TITLE
Problem install superdesk publisher Ubuntu 16.04 (two servers)

### ISSUE THREAD

**Issue by d1mf** [superdesk/web-publisher#580]
Hello.
I want to install superdesk publisher. I using this manual.

http://superdesk-publisher.readthedocs.io/en/latest/manual/getting_started/superdesk-superdesk-publisher-setup.html
1) I have two servers ubuntu 16.04 ( 1 server superdesk) (2 server superdesk publish)
2) I install superdesk http://prntscr.com/k8zl34 and install superdesk publish  http://prntscr.com/k8zl91
3) I check all logs nginx,rabbitmq server, and supervisor+ config symphony. Not find, why server not working. I see this window http://prntscr.com/k8zlqn http://prntscr.com/k8zlv6
I think superdesk publish not loading. 
I think superdesk server just using API http port 80. What problem?
I testing docker this 100% not working.

If need I can send configs. Please help. Thanks.

**Comment by ahilles107** [comment]
Hey, looks like Superdesk can't connect to Your publisher instance. Can you check in networking tab in developers tools what error you have for calls to publisher? One more thing. Check if your superdesk user have firstname and lastname provided (it's know bug not fixed yet in publisher).

**Comment by d1mf** [comment]
I change. same problem

**Comment by ahilles107** [comment]
And what do you have in response from server for publisher api `tenants` request?

**Comment by d1mf** [comment]
I see interesting error
prod.log

[2018-07-20 12:23:25] console.ERROR: Error thrown while running command "rabbitmq:consumer send_webhook --messages=250 --env=prod". Message: "stream_socket_client(): unable to connect to tcp://127.0.0.1:5672 (Connection refused)" {"exception":"[object] (ErrorException(code: 0): stream_socket_client(): unable to connect to tcp://127.0.0.1:5672 (Connection refused) at /var/www/publisher/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:141)","command":"rabbitmq:consumer send_webhook --messages=250 --env=prod","message":"stream_socket_client(): unable to connect to tcp://127.0.0.1:5672 (Connection refused)"} []
[2018-07-20 12:23:25] console.DEBUG: Command "rabbitmq:consumer analytics_event --messages=250 --env=prod" exited with code "1" {"command":"rabbitmq:consumer analytics_event --messages=250 --env=prod","code":1} []
[2018-07-20 12:23:25] console.DEBUG: Command "rabbitmq:consumer send_webhook --messages=250 --env=prod" exited with code "1" {"command":"rabbitmq:consumer send_webhook --messages=250 --env=prod","code":1} []

12:23:25 ERROR     [console] Error thrown while running command "rabbitmq:consumer send_webhook --messages=250 --env=prod". Message: "stream_socket_client(): unable to connect to tcp://127.0.0.1:5672 (Connection refused)" ["exception" => ErrorException { …},"command" => "rabbitmq:consumer send_webhook --messages=250 --env=prod","message" => "stream_socket_client(): unable to connect to tcp://127.0.0.1:5672 (Connection refused)"] []

In StreamIO.php line 141:

  stream_socket_client(): unable to connect to tcp://127.0.0.1:5672 (Connecti
  on refused)

stderr.log

rabbitmq:consumer [-m|--messages [MESSAGES]] [-r|--route [ROUTE]] [-l|--memory-limit [MEMORY-LIMIT]] [-d|--debug] [-w|--without-signals] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [-t|--tenant TENANT] [--] <command> <name>

I testing. rabbimq working.

http://prntscr.com/k90fyl

login and user test

If you need, I can provide SSH.

**Comment by ahilles107** [comment]
It's not related to super desk issue. Probably you have some issues with rabbit login config. ` unable to connect to tcp://127.0.0.1:5672 (Connection refused)` - it's clear permissions error on rabbit side.

**Comment by d1mf** [comment]
http://prntscr.com/k90fyl - I enable plugin web UI all fine. And I testing python script auth rabbit - all fine.
I check logs 

=INFO REPORT==== 20-Jul-2018::12:23:27 ===
Server startup complete; 6 plugins started.
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * webmachine
 * mochiweb
 * rabbitmq_management_agent
 * amqp_client

=INFO REPORT==== 20-Jul-2018::12:23:27 ===
accepting AMQP connection <0.322.0> (127.0.0.1:57908 -> 127.0.0.1:5672)

=INFO REPORT==== 20-Jul-2018::12:23:27 ===
accepting AMQP connection <0.332.0> (127.0.0.1:57910 -> 127.0.0.1:5672)

=INFO REPORT==== 20-Jul-2018::12:34:28 ===
closing AMQP connection <0.322.0> (127.0.0.1:57908 -> 127.0.0.1:5672)

=INFO REPORT==== 20-Jul-2018::12:34:28 ===
closing AMQP connection <0.332.0> (127.0.0.1:57910 -> 127.0.0.1:5672)

=INFO REPORT==== 20-Jul-2018::12:34:29 ===
accepting AMQP connection <0.555.0> (127.0.0.1:57968 -> 127.0.0.1:5672)

=INFO REPORT==== 20-Jul-2018::12:34:29 ===
accepting AMQP connection <0.565.0> (127.0.0.1:57970 -> 127.0.0.1:5672)

**Comment by ahilles107** [comment]
ok, let's solve first issue with missing data in publisher ui. Rabbit not related here. Show me what response you have for request from super desk to publisher (network tab when you load output control view - https://prnt.sc/k8zlqn)

**Comment by d1mf** [comment]
What do you mean?  You mean request curl?

**Comment by ahilles107** [comment]
<img width="874" alt="zrzut ekranu 2018-07-20 o 21 54 00" src="https://user-images.githubusercontent.com/298610/43022403-767049ec-8c67-11e8-9a4c-fd54d0458a4e.png">

This view ;)

**Comment by d1mf** [comment]
![screenshot_105](https://user-images.githubusercontent.com/10393074/43022589-6d3bf9e4-8c70-11e8-8dac-245cca440ffb.jpg)
![screenshot_106](https://user-images.githubusercontent.com/10393074/43022591-6d57bb7a-8c70-11e8-9d5e-832b8ade92f7.jpg)

**Comment by d1mf** [comment]
I change null to ""
![screenshot_107](https://user-images.githubusercontent.com/10393074/43022645-975f3fce-8c70-11e8-885c-c44042ab1f48.jpg)
![screenshot_108](https://user-images.githubusercontent.com/10393074/43022646-977ad806-8c70-11e8-886f-332b3660b752.jpg)

**Comment by ahilles107** [comment]
You see? Request goes to null.192.168.1.12. Please change `tenant: '',` to `tenant: null,` like I asked. 

`'' !== null`

**Comment by ahilles107** [comment]
Ahh i see - so it works now? Do You have organization and tenants created?

**Comment by d1mf** [comment]
Not work. 
You mean this?
Organization Publisher (code: 69em0e) has been created and enabled!
Tenant Testing (code: 0jytgu) has been created and enabled!
Or need create using web ui?

**Comment by ahilles107** [comment]
what do you get from this `superdesk/` GET request (second one). You should have auth token there. And ui should run next calls for tenants and routes.

**Comment by ahilles107** [comment]
You can also change in `parameters.yml`

`allow_origin_cors: '*'` to `allow_origin_cors: '192.168.1.6'`

**Comment by d1mf** [comment]
You mean this?

http://192.168.1.12/api/v1/auth/superdesk
![screenshot_109](https://user-images.githubusercontent.com/10393074/43023277-f2d9f496-8c72-11e8-9693-055d6b1c5129.jpg)
![screenshot_110](https://user-images.githubusercontent.com/10393074/43023279-f32881e2-8c72-11e8-8fb3-956f6a3a6375.jpg)

**Comment by ahilles107** [comment]
I see you have just options. So it's because this `allow_origin_cors`. After changing it to `allow_origin_cors: '192.168.1.6'` You need to clear cache (`rm -rf app/cache/prod/*`).

**Comment by ahilles107** [comment]
You can see that `Access-Control-Allow-Origin` is still null. So something is wrong. I just checked and on our demo we have it set to `allow_origin_cors: '*'` so looks like Your nginx is setting this header manually. You can try to hardcore it in your ngins host config (https://serverfault.com/questions/162429/how-do-i-add-access-control-allow-origin-in-nginx). Without this browser will not send get requests to publisher.

**Comment by d1mf** [comment]
Edit server superdesk publisher or superdesk?

**Comment by ahilles107** [comment]
Superdesk Publisher.

**Comment by d1mf** [comment]
This original file( download from manual install)

server {
    listen 80 default;
    root /var/www/publisher/web;

    location / {
        try_files $uri /app.php$is_args$args;
    }




    location ~ ^/(app|app_dev|config)\.php(/|$) {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }
}

I edit to 
server {
    listen 80 default;
    root /var/www/publisher/web;

    location / {
	 add_header Access-Control-Allow-Origin *;
        try_files $uri /app.php$is_args$args;
		
    }




    location ~ ^/(app|app_dev|config)\.php(/|$) {
	 add_header Access-Control-Allow-Origin *;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

**Comment by ahilles107** [comment]
restart nginx after this change (or reload config).

**Comment by d1mf** [comment]
Done

![screenshot_113](https://user-images.githubusercontent.com/10393074/43024367-d1bab33c-8c76-11e8-8a8f-6a0004ac7b24.jpg)
![Uploading Screenshot_114.jpg…]()

**Comment by ahilles107** [comment]
Not sure it this `null` isn't problematic. browser still don't send GET request to this endpoint.

**Comment by ahilles107** [comment]
Yep: https://stackoverflow.com/questions/18945158/chrome-origin-null-is-not-allowed-by-access-control-allow-origin

**Comment by ahilles107** [comment]
We need to get rid of this `null`. Question is - why Publisher don't set it correctly. 

Try to change `allow_origin_cors: '*'` in parameters.yml to `allow_origin_cors: ['*']`

**Comment by d1mf** [comment]
I see. Am I using config nginx in manual. What needs an edit?
   root /var/www/publisher/web; to    root /var/www/publisher/; ?

**Comment by ahilles107** [comment]
Root is ok. try with * in array. I have hope that it will fix it.

**Comment by d1mf** [comment]
![screenshot_115](https://user-images.githubusercontent.com/10393074/43024955-9e20fab6-8c78-11e8-9765-05c28650fbd9.jpg)
This yes?

**Comment by ahilles107** [comment]
It looks ok. I have no idea why next requests are not created by browser. You can try to remove that hardcoded add_header from config and in parameters set `*` instead ip address. Check also console tab - maybe there is some js error.

**Comment by d1mf** [comment]
I remove add_header from config nginx
and I see error 500 superdesk

![screenshot_116](https://user-images.githubusercontent.com/10393074/43025246-9d778e8a-8c79-11e8-81b1-81233fc10ebe.jpg)
![screenshot_117](https://user-images.githubusercontent.com/10393074/43025255-a7518910-8c79-11e8-9f9e-49e75c6f41dd.jpg)

**Comment by ahilles107** [comment]
ok, go to your super desk user profile (right top corner and edit profile - set first and last name there)

**Comment by d1mf** [comment]
Done

**Comment by d1mf** [comment]
I see new loading page

![screenshot_118](https://user-images.githubusercontent.com/10393074/43025517-c473557c-8c7a-11e8-90d7-6e1c3c800e9c.jpg)
![Uploading Screenshot_119.jpg…]()

**Comment by d1mf** [comment]
testing I think this my server SP

![screenshot_120](https://user-images.githubusercontent.com/10393074/43025557-e531ef3a-8c7a-11e8-9566-7ffd7bf4a61e.jpg)

**Comment by ahilles107** [comment]
Looks like it's solved ;) We will adjust install instructions to use `['*']`

**Comment by d1mf** [comment]
Good. And next step check rabbitmq?

**Comment by ahilles107** [comment]
You can use `/app_dev.php/` for development - it will tell you more about theme and queries. Now you need some routes, rules and published content. Rabbit looks like php-rabbit connection issue. check if your credentials are ok in parameters.yml. Try to google that issue.

**Comment by d1mf** [comment]
I think now  S show me server SP.
And I have problem rabbitmq. ( I send earlier logs)
I also wanted to ask for what answers rabbitmq?

**Comment by d1mf** [comment]
![screenshot_121](https://user-images.githubusercontent.com/10393074/43025690-70f56984-8c7b-11e8-906d-242424914b2b.jpg)
![Uploading Screenshot_122.jpg…]()

**Comment by d1mf** [comment]
I using easy login and pass
test and test

I see  rabbitmq load
I download python script( testing connect). Result - ok

**Comment by d1mf** [comment]
And this output app_dev.php

![screenshot_123](https://user-images.githubusercontent.com/10393074/43025747-a0fad25e-8c7b-11e8-9e1e-f432f0142b01.jpg)

**Comment by ahilles107** [comment]
run `composer install --dev` to use app_dev. For rabbit we use this library: https://github.com/php-amqplib/php-amqplib Make sure that you have all php extensions enabled and you can connect to rabbit from php script.

**Comment by d1mf** [comment]
And I want install superdesk and superdesk publish to 1 server. This possible?

**Comment by ahilles107** [comment]
That's weird - looks like it can't be array but id didn't worked with string.

**Comment by d1mf** [comment]
Problem config  parameters.yml?

**Comment by ahilles107** [comment]
Yep, looks like nelmio cors bundle don't allow `['*']` But this is how it's in their docs. I will try to check it on Monday.

**Comment by d1mf** [comment]
I testing edit to '*'  - same problem

**Comment by d1mf** [comment]
How are you?
